server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
  servlet:
    context-path:
  port: 8150

spring:
  application:
    name: watch-film-stat-server
  sql:
    init:
      mode: always
      #      mode: never
      data-locations: "classpath:data.sql"
      schema-locations: "classpath:schema.sql"

  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    url: jdbc:postgresql://localhost:5430/db
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    #      ddl-auto: create
    #      ddl-auto: none


  kafka:
    consumer:
      group-id: "watch-notify-group"
      bootstrap-servers: "localhost:9092"
      client-id: "watch-notify-consumer"
      auto-offset-reset: earliest

application:
  kafka:
    topic: "watch-notify-topic"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

